# Copyright © 2020 Property of Rían Errity Licensed under GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007. See <LICENSE.md>
name: Report
version: ${project.version}
main: io.paradaux.report.Report
api-version: 1.13
commands:
  report:
    usage: /report <bug/player> (<player>) <issue>

